services:
  backend:
    container_name: backend
    build: 
      context: ./backend
      target: prod
    ports:
      - "8000:8000"
    volumes:
      - logs:/app/logs
    depends_on:
      - filebeat

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      target: prod
    volumes:
      - node_modules:/app/node_modules

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      target: prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
      - xpack.security.enabled=false
    networks:
      - efk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://35.175.104.173:9200
    networks:
      - efk
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.0
    container_name: filebeat
    command: filebeat -e -strict.perms=false
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - logs:/usr/share/filebeat/logs
    environment:
      ELASTICSEARCH_URL: http://35.175.104.173:9200
    networks:
      - efk
    links:
      - kibana
      - elasticsearch
    depends_on:
      - elasticsearch


networks:
  efk:
    driver: bridge

volumes:
  node_modules:
  logs: