services:
  backend:
    container_name: backend
    build: 
      context: ./backend
    ports:
      - "8000:8000"

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
    volumes:
      - node_modules:/home/app/node_modules

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
    ports:
      - "3000:80"
    depends_on:
      - backend
      - frontend

volumes:
  node_modules: