services:
  backend:
    container_name: backend
    build: 
      context: ./backend
    ports:
      - "8000:8000"

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend

volumes:
  node_modules: