services:
  backend:
    container_name: backend
    build: 
      context: ./backend
      target: prod
    ports:
      - "8000:8000"

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      target: prod
    volumes:
      - node_modules:/app/node_modules

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      target: prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend

volumes:
  node_modules: