# Generated by Django 5.0.7 on 2024-08-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='cards/images/'),
        ),
    ]
